### ISSUE TITLE
Issue with docker user management

### ISSUE THREAD

**Issue by Inarisee** [cdwiegand/getmail-docker-maildir#1]
I guess this is not an issue in the given container but may lead to an improvement. I´m quite stuck with this:
I do get the following error:

  msg    33/16158 (32650 bytes), delivery error (maildir delivery 40 error (127, maildir delivery process failed (refuse to deliver mail as root)))

How did you overcome that problem?

**Comment by cdwiegand** [comment]
Check your filesystem permissions for the mounted `/maildir` folder for user ID 8 (mail), and set getmailrc file:
```
[destination]
user = mail
```

I've got my `/maildir/new` folder set to 777 permissions, and it's using uid 8 as the mail user as far as I can tell.
